// Healthcare Program Templates - pre-computed program structures
// Provides instant drafts for common healthcare program types.

import type { ToCData, LogframeData } from './types'
import type { ProgramTemplate } from './program-templates'

export const HEALTHCARE_TEMPLATES: ProgramTemplate[] = [
  {
    id: 'chw-program',
    name: 'Community Health Worker Program',
    category: 'Health',
    description: 'Deploy CHWs for integrated maternal/child health, based on WHO CHW guidelines (2018) and Rwanda/Ethiopia models.',
    icon: 'Users',
    problem: 'Design a community health worker program to deploy [NUMBER] CHWs across [NUMBER] districts in [LOCATION], providing maternal/child health, immunization, and nutrition services to [NUMBER] people. Budget [BUDGET] over [DURATION].',
    estimatedDuration: '3-5 years',
    typicalBudget: '$500K - $5M',
    toc: {
      targetPopulation: 'Pregnant women, lactating mothers, and children under 5 in target districts',
      inputs: [
        'CHW selection criteria and recruitment (community-nominated, literate, female-majority)',
        'Training curriculum (initial 3-week + monthly refresher)',
        'CHW kits (weighing scale, MUAC tape, thermometer, first-aid, referral forms)',
        'Mobile phones with CHW app (for registration, follow-up, reporting)',
        'Supervision system (1 supervisor per 20-25 CHWs)',
        'Essential medicines and commodities (ORS, zinc, amoxicillin, malaria RDTs, ACTs)',
        'Referral transport (emergency transport fund or ambulance linkage)',
        'M&E framework aligned to DHIS2',
      ],
      activities: [
        'Recruit and train CHWs (1 per 500 households)',
        'Conduct household registration and mapping',
        'Monthly household visits for pregnant women and children under 2',
        'Provide integrated community case management (iCCM) for malaria, pneumonia, diarrhea',
        'Screen for malnutrition (MUAC) and refer severe cases',
        'Promote immunization and track defaulters',
        'Facilitate birth preparedness and emergency referrals',
        'Conduct monthly supervision and data review meetings',
        'Report into DHIS2 via mobile app',
      ],
      outputs: [
        '[NUMBER] CHWs recruited, trained, and deployed',
        '[NUMBER] households registered and mapped',
        '[NUMBER] pregnant women receiving monthly ANC counseling visits',
        '[NUMBER] children under 5 receiving iCCM services',
        '[NUMBER] malnutrition cases screened and referred',
        'Monthly DHIS2 reports submitted by [X]% of CHWs',
      ],
      outcomes: [
        'X% of pregnant women receiving 4+ ANC visits (from Y% baseline)',
        'X% of deliveries at health facilities (from Y% baseline)',
        'X% of children with fever/diarrhea/pneumonia receiving treatment within 24 hours',
        'X% of children fully immunized by age 1 (from Y% baseline)',
        'X% reduction in severe acute malnutrition cases',
      ],
      impact: 'Reduced maternal mortality ratio and under-5 mortality rate in target districts, contributing to national SDG 3 targets',
      assumptions: [
        'CHWs are retained with adequate incentives (stipend + career pathway)',
        'Essential medicines and supplies are consistently available',
        'Referral health facilities are functional and accessible',
        'Communities accept and trust CHWs',
        'Government commits to absorbing CHWs into the health system',
      ],
      externalFactors: [
        'Health facility readiness and quality of care at referral level',
        'Disease outbreaks affecting program implementation',
        'Government health workforce policy changes',
        'Supply chain disruptions for essential medicines',
        'Security situation in target areas',
      ],
    },
    logframe: {
      goal: {
        level: 'Goal',
        description: 'Reduced maternal and under-5 mortality in target districts',
        ovi: 'Maternal mortality ratio; under-5 mortality rate (per DHS/HMIS)',
        mov: 'DHS surveys; HMIS/DHIS2 data; vital registration',
        assumptions: 'CHW program contributes to mortality reduction alongside facility strengthening',
      },
      purpose: {
        level: 'Purpose',
        description: 'Women and children in target communities access timely, quality health services through CHWs',
        ovi: 'X% 4+ ANC; X% facility delivery; X% iCCM treatment within 24h; X% full immunization',
        mov: 'CHW registers; DHIS2 reports; household surveys',
        assumptions: 'CHW visits lead to improved care-seeking behavior',
      },
      outputs: [
        {
          level: 'Output',
          description: 'CHWs recruited, trained, equipped, and deployed',
          ovi: '[NUMBER] CHWs; 1 per 500 HH; 3-week training; kit and phone provided',
          mov: 'Training records; deployment register; equipment inventory',
          assumptions: 'Suitable candidates available; training quality maintained',
        },
        {
          level: 'Output',
          description: 'Households registered and receiving regular visits',
          ovi: '[NUMBER] HH registered; monthly visits to pregnant women and children under 2',
          mov: 'CHW mobile app data; DHIS2 reports; spot checks',
          assumptions: 'Households accept visits; CHWs cover assigned catchment area',
        },
        {
          level: 'Output',
          description: 'Community case management services delivered',
          ovi: '[NUMBER] children treated for malaria/diarrhea/pneumonia; [NUMBER] referrals made',
          mov: 'Treatment registers; referral forms; facility confirmation',
          assumptions: 'Medicines available; CHWs follow iCCM protocols',
        },
        {
          level: 'Output',
          description: 'Supervision system functional',
          ovi: '1 supervisor per 20-25 CHWs; monthly supervision visits; quarterly data review',
          mov: 'Supervision checklists; meeting minutes; performance dashboards',
          assumptions: 'Supervisors have transport and time; supervision is supportive not punitive',
        },
      ],
      activities: [
        { level: 'Activity', description: 'CHW recruitment and training', ovi: '3-week initial training; competency assessment', mov: 'Training reports; test scores', assumptions: 'Training facilities and materials available' },
        { level: 'Activity', description: 'Household registration and mapping', ovi: 'Complete in first 2 months post-deployment', mov: 'Registration data in CHW app', assumptions: 'Communities cooperate with registration' },
        { level: 'Activity', description: 'Monthly household visits', ovi: 'All pregnant women and children under 2 visited monthly', mov: 'Visit logs in CHW app', assumptions: 'CHWs have time and motivation' },
        { level: 'Activity', description: 'iCCM service delivery', ovi: 'Treatment per national protocol', mov: 'Treatment registers; medicine consumption', assumptions: 'Medicine supply maintained' },
        { level: 'Activity', description: 'Monthly supervision and data review', ovi: 'Each CHW supervised monthly; district data review quarterly', mov: 'Supervision reports; meeting minutes', assumptions: 'Supervisors trained and equipped' },
      ],
    },
    budget: [
      { category: 'CHW stipends/incentives', percentage: 30, description: 'Monthly stipends, performance bonuses, mobile airtime' },
      { category: 'Training (initial + refresher)', percentage: 15, description: '3-week initial, monthly refresher, supervisor training' },
      { category: 'Equipment and supplies', percentage: 15, description: 'CHW kits, mobile phones, essential medicines' },
      { category: 'Supervision and transport', percentage: 15, description: 'Supervisor salaries, motorcycles, fuel' },
      { category: 'Digital health tools', percentage: 10, description: 'CHW app development/licensing, data hosting, DHIS2 integration' },
      { category: 'M&E and research', percentage: 10, description: 'Baseline/endline surveys, data quality audits, operational research' },
      { category: 'Administration and overhead', percentage: 5, description: 'Office, coordination, communications' },
    ],
    risks: [
      { risk: 'CHW attrition (>20% annually)', likelihood: 'High', impact: 'High', mitigation: 'Adequate stipend; career pathway (CHW → health assistant); recognition; train replacements pipeline' },
      { risk: 'Medicine and supply stockouts', likelihood: 'Medium', impact: 'High', mitigation: '3-month buffer stock; multiple suppliers; real-time stock monitoring via app' },
      { risk: 'Low quality of CHW services', likelihood: 'Medium', impact: 'High', mitigation: 'Monthly supportive supervision; competency-based refresher training; clinical audits' },
      { risk: 'Referral facility non-functional', likelihood: 'Medium', impact: 'High', mitigation: 'Map functional facilities; emergency transport fund; facility readiness support' },
      { risk: 'Government does not absorb CHWs', likelihood: 'Medium', impact: 'High', mitigation: 'Early MOU with Ministry of Health; advocacy for CHW policy; phased co-financing' },
    ],
  },
  {
    id: 'immunization-coverage',
    name: 'Immunization Coverage Improvement',
    category: 'Health',
    description: 'Reach zero-dose children using RED/REC strategy, cold chain strengthening, and community demand generation.',
    icon: 'Shield',
    problem: 'Design a program to improve immunization coverage in [NUMBER] underserved districts in [LOCATION] where DPT3 coverage is below [X]%. Reach zero-dose children, strengthen cold chain, and build community demand. Budget [BUDGET] over [DURATION].',
    estimatedDuration: '2-3 years',
    typicalBudget: '$200K - $2M',
    toc: {
      targetPopulation: 'Children 0-23 months in underserved districts, with focus on zero-dose children',
      inputs: [
        'Cold chain equipment (solar refrigerators, vaccine carriers, ice packs)',
        'Vaccines (from UNICEF Supply Division or national procurement)',
        'Trained vaccinators and cold chain technicians',
        'Microplanning tools and maps',
        'Community mobilizers and health education materials',
        'Data tools (immunization registers, DHIS2 module, defaulter tracking)',
        'Transport for outreach sessions',
      ],
      activities: [
        'Conduct cold chain assessment and repair/replace equipment',
        'Train health workers on RED/REC strategy and microplanning',
        'Develop microplans for every health facility catchment area',
        'Conduct monthly fixed-site and outreach immunization sessions',
        'Identify and track zero-dose and defaulter children',
        'Engage community leaders, religious leaders, and women groups for demand generation',
        'Address vaccine hesitancy through dialogue and social media',
        'Strengthen routine data reporting into DHIS2',
        'Conduct quarterly EPI review meetings at district level',
      ],
      outputs: [
        '[NUMBER] health facilities with functional cold chain',
        '[NUMBER] health workers trained on RED/REC',
        'Microplans developed for [NUMBER] catchment areas',
        '[NUMBER] outreach sessions conducted per month',
        '[NUMBER] zero-dose children identified and vaccinated',
        'Immunization data reported into DHIS2 monthly',
      ],
      outcomes: [
        'DPT3 coverage increased from [X]% to [Y]% in target districts',
        'Zero-dose children reduced by [X]% in target districts',
        'Dropout rate (DPT1-DPT3) reduced to below 10%',
        'Cold chain functionality maintained at >90% of facilities',
        'Community demand for vaccination increased (measured by voluntary attendance)',
      ],
      impact: 'Reduced vaccine-preventable disease morbidity and mortality in target districts, contributing to national immunization targets and global polio/measles elimination goals',
      assumptions: [
        'Vaccine supply is reliable from national level',
        'Health workers are available and motivated',
        'Communities are willing to vaccinate when services are accessible',
        'Cold chain equipment is maintained',
        'Security allows outreach to remote areas',
      ],
      externalFactors: [
        'Global vaccine supply disruptions',
        'Vaccine hesitancy driven by misinformation',
        'Disease outbreaks requiring emergency response',
        'Political instability or conflict',
        'Climate events affecting accessibility',
      ],
    },
    logframe: {
      goal: {
        level: 'Goal',
        description: 'Reduced vaccine-preventable disease morbidity and mortality in target districts',
        ovi: 'Measles incidence; neonatal tetanus cases; VPD-related under-5 deaths',
        mov: 'Disease surveillance data; HMIS; survey data',
        assumptions: 'Improved coverage translates to reduced disease burden',
      },
      purpose: {
        level: 'Purpose',
        description: 'Children 0-23 months in target districts are fully immunized according to national schedule',
        ovi: 'DPT3 coverage ≥90%; measles coverage ≥95%; zero-dose <5%',
        mov: 'DHIS2 administrative data; coverage surveys',
        assumptions: 'Vaccine supply and cold chain are sustained',
      },
      outputs: [
        {
          level: 'Output',
          description: 'Cold chain strengthened',
          ovi: '[NUMBER] facilities with functional cold chain; >90% functionality rate',
          mov: 'Cold chain inventory; temperature monitoring logs',
          assumptions: 'Equipment is maintained; solar power reliable',
        },
        {
          level: 'Output',
          description: 'Health workers trained and microplans implemented',
          ovi: '[NUMBER] workers trained; microplans for all catchment areas',
          mov: 'Training records; microplan documents',
          assumptions: 'Workers apply training; microplans are updated quarterly',
        },
        {
          level: 'Output',
          description: 'Outreach and defaulter tracking operational',
          ovi: 'Monthly outreach sessions; defaulter tracking within 2 weeks',
          mov: 'Session reports; defaulter tracking registers',
          assumptions: 'Transport available; communities accessible',
        },
      ],
      activities: [
        { level: 'Activity', description: 'Cold chain assessment and rehabilitation', ovi: 'Completed in months 1-3', mov: 'Assessment report; procurement records', assumptions: 'Equipment available for procurement' },
        { level: 'Activity', description: 'Health worker training on RED/REC', ovi: '5-day training for [NUMBER] workers', mov: 'Training reports', assumptions: 'Workers released for training' },
        { level: 'Activity', description: 'Microplanning', ovi: 'Plans developed for all catchment areas by month 4', mov: 'Microplan documents', assumptions: 'Population data available' },
        { level: 'Activity', description: 'Community demand generation', ovi: 'Monthly mobilization activities', mov: 'Activity reports; community meeting minutes', assumptions: 'Community leaders supportive' },
      ],
    },
    budget: [
      { category: 'Cold chain equipment', percentage: 25, description: 'Solar refrigerators, vaccine carriers, temperature monitors' },
      { category: 'Outreach and transport', percentage: 20, description: 'Vehicles, fuel, per diems for outreach sessions' },
      { category: 'Training', percentage: 15, description: 'RED/REC training, microplanning workshops, cold chain maintenance' },
      { category: 'Community mobilization', percentage: 15, description: 'Mobilizers, IEC materials, community dialogues' },
      { category: 'Data systems', percentage: 10, description: 'DHIS2 module, registers, defaulter tracking tools' },
      { category: 'Supervision and review', percentage: 10, description: 'Quarterly reviews, supportive supervision, data quality audits' },
      { category: 'Administration', percentage: 5, description: 'Coordination, communications' },
    ],
    risks: [
      { risk: 'Vaccine supply disruption', likelihood: 'Medium', impact: 'High', mitigation: 'Buffer stock; multiple supply channels; early forecasting' },
      { risk: 'Vaccine hesitancy/refusal', likelihood: 'Medium', impact: 'High', mitigation: 'Community dialogue; religious leader engagement; address specific concerns' },
      { risk: 'Cold chain breakdown', likelihood: 'Medium', impact: 'High', mitigation: 'Preventive maintenance; backup equipment; trained technicians' },
      { risk: 'Inaccessible populations (nomadic, conflict)', likelihood: 'High', impact: 'Medium', mitigation: 'Mobile teams; negotiated access; special strategies for nomadic populations' },
    ],
  },
  {
    id: 'phc-strengthening',
    name: 'Primary Healthcare Strengthening',
    category: 'Health',
    description: 'Improve quality of care at primary health facilities using WHO building blocks and CQI approach.',
    icon: 'Building',
    problem: 'Design a primary healthcare strengthening program for [NUMBER] health facilities in [LOCATION] to improve quality and coverage of essential health services. Budget [BUDGET] over [DURATION].',
    estimatedDuration: '3-5 years',
    typicalBudget: '$1M - $10M',
    toc: {
      targetPopulation: 'Population served by target primary health facilities (health centers and health posts)',
      inputs: [
        'Clinical guidelines and standard operating procedures',
        'Essential medicines and medical supplies (per WHO EML)',
        'Medical equipment (basic diagnostic, maternal health, emergency)',
        'Health worker training (clinical skills, CQI methodology)',
        'Quality improvement coaches',
        'HMIS/DHIS2 strengthening (tools, training, connectivity)',
        'Infrastructure improvements (water, electricity, waste management)',
        'Community feedback mechanisms',
      ],
      activities: [
        'Conduct facility readiness assessment (using WHO SARA tool)',
        'Develop facility improvement plans based on assessment',
        'Train health workers on clinical protocols (IMNCI, BEmONC, essential care)',
        'Establish quality improvement teams at each facility',
        'Implement PDSA cycles for priority quality gaps',
        'Strengthen medicine supply chain and stock management',
        'Improve HMIS data quality and use for decision-making',
        'Establish community health committees and feedback mechanisms',
        'Conduct quarterly supportive supervision and mentoring',
        'Facilitate peer learning through QI collaboratives',
      ],
      outputs: [
        '[NUMBER] facilities assessed and improvement plans developed',
        '[NUMBER] health workers trained on clinical protocols',
        'QI teams functional at [NUMBER] facilities',
        '[NUMBER] PDSA cycles completed',
        'Essential medicine availability at >80% of facilities',
        'DHIS2 reporting completeness at >90%',
      ],
      outcomes: [
        'X% improvement in clinical care quality scores (measured by clinical vignettes or observation)',
        'X% increase in essential medicine availability',
        'X% improvement in patient satisfaction',
        'X% increase in outpatient visits (indicating increased utilization)',
        'X% improvement in DHIS2 data quality and timeliness',
        'Reduction in unnecessary referrals to district hospital',
      ],
      impact: 'Improved health outcomes and reduced mortality through higher quality primary healthcare, contributing to universal health coverage',
      assumptions: [
        'Government supports quality improvement approach',
        'Health workers are motivated to improve',
        'Medicine supply chain can be strengthened',
        'Facilities have minimum infrastructure (or can be upgraded)',
        'District health management team engages actively',
      ],
      externalFactors: [
        'Government health budget and fiscal space',
        'Health worker strikes or industrial action',
        'Disease outbreaks diverting resources',
        'Policy changes affecting PHC delivery',
        'Infrastructure challenges (electricity, water, roads)',
      ],
    },
    logframe: {
      goal: {
        level: 'Goal',
        description: 'Improved health outcomes through quality primary healthcare in target areas',
        ovi: 'Maternal mortality ratio; under-5 mortality; NCD management outcomes',
        mov: 'HMIS/DHIS2; population surveys; vital registration',
        assumptions: 'Quality improvement translates to better health outcomes',
      },
      purpose: {
        level: 'Purpose',
        description: 'Target health facilities deliver quality essential health services with improved coverage',
        ovi: 'Quality of care score; essential medicine availability; patient satisfaction; utilization rates',
        mov: 'Facility assessments; patient exit interviews; DHIS2 data',
        assumptions: 'Improved quality increases utilization and outcomes',
      },
      outputs: [
        {
          level: 'Output',
          description: 'Health workers competent in clinical protocols',
          ovi: '[NUMBER] workers trained; competency scores >80%',
          mov: 'Training records; competency assessments; clinical observation',
          assumptions: 'Workers apply skills in practice',
        },
        {
          level: 'Output',
          description: 'QI teams functional and implementing PDSA cycles',
          ovi: 'QI teams at [NUMBER] facilities; minimum 4 PDSA cycles per year',
          mov: 'QI team meeting minutes; PDSA documentation; change tracking',
          assumptions: 'Teams have protected time for QI activities',
        },
        {
          level: 'Output',
          description: 'Essential medicines and supplies available',
          ovi: 'Tracer medicines available at >80% of facilities; no stockouts >1 week',
          mov: 'Stock monitoring; facility assessment; LMIS data',
          assumptions: 'National supply chain functions adequately',
        },
        {
          level: 'Output',
          description: 'HMIS data quality improved and used for decisions',
          ovi: 'Reporting completeness >90%; data accuracy >85%; quarterly data review meetings held',
          mov: 'DHIS2 reports; DQA results; meeting minutes',
          assumptions: 'Staff see value in data; connectivity available',
        },
      ],
      activities: [
        { level: 'Activity', description: 'Facility readiness assessment (SARA)', ovi: 'All facilities assessed in months 1-2', mov: 'SARA reports', assumptions: 'Assessment tools and assessors available' },
        { level: 'Activity', description: 'Clinical skills training', ovi: '10-day training per cadre', mov: 'Training reports; pre/post tests', assumptions: 'Workers released for training' },
        { level: 'Activity', description: 'QI team establishment and coaching', ovi: 'Teams formed by month 3; monthly coaching visits', mov: 'Team records; coaching reports', assumptions: 'Facility in-charges support QI' },
        { level: 'Activity', description: 'Supply chain strengthening', ovi: 'LMIS implemented; ordering cycle established', mov: 'LMIS reports; order records', assumptions: 'National supply system responsive' },
        { level: 'Activity', description: 'Supportive supervision', ovi: 'Quarterly visits to each facility', mov: 'Supervision reports; action plans', assumptions: 'Supervisors have transport and skills' },
      ],
    },
    budget: [
      { category: 'Training and capacity building', percentage: 25, description: 'Clinical training, QI methodology, data use, supervision skills' },
      { category: 'Equipment and infrastructure', percentage: 20, description: 'Medical equipment, minor renovations, water/solar' },
      { category: 'Quality improvement coaching', percentage: 15, description: 'QI coaches, mentoring visits, collaborative learning sessions' },
      { category: 'Supply chain strengthening', percentage: 15, description: 'LMIS tools, stock management training, buffer stock support' },
      { category: 'Data systems', percentage: 10, description: 'DHIS2 strengthening, connectivity, data quality audits' },
      { category: 'Supervision and management', percentage: 10, description: 'Supportive supervision, district management capacity' },
      { category: 'Administration', percentage: 5, description: 'Coordination, communications, overhead' },
    ],
    risks: [
      { risk: 'Health worker demotivation or turnover', likelihood: 'High', impact: 'High', mitigation: 'Supportive (not punitive) supervision; recognition; involvement in QI decisions' },
      { risk: 'Medicine supply chain failure', likelihood: 'Medium', impact: 'High', mitigation: 'Strengthen LMIS; advocate for budget; identify alternative supply sources' },
      { risk: 'Government deprioritizes PHC', likelihood: 'Medium', impact: 'High', mitigation: 'Advocacy with evidence; align with national health strategy; demonstrate cost-effectiveness' },
      { risk: 'QI fatigue (too many changes)', likelihood: 'Medium', impact: 'Medium', mitigation: 'Prioritize 2-3 changes at a time; celebrate wins; protect QI time' },
      { risk: 'Infrastructure barriers (no water/electricity)', likelihood: 'High', impact: 'Medium', mitigation: 'Include basic infrastructure in budget; solar solutions; rainwater harvesting' },
    ],
  },
]

export function getHealthcareTemplateById(id: string): ProgramTemplate | undefined {
  return HEALTHCARE_TEMPLATES.find((t) => t.id === id)
}
